// Copyright The prometheus-operator Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package crd provides access to the embedded CRD manifests.
// The CRD YAML files are generated by controller-gen in the
// prometheus-operator-crd subdirectory and embedded into the
// operator binary at build time.
package crd

import (
	"embed"
	"fmt"
	"io"
	"io/fs"
	"slices"
	"strings"
)

// Embed all CRD YAML files into the binary.
// These files are the source CRDs generated by controller-gen.
//
//go:embed prometheus-operator-crd/*.yaml
var embeddedCRDs embed.FS

const crdsDir = "prometheus-operator-crd"

// PrintAll prints all embedded CRDs to the given writer.
// CRDs are printed in alphabetical order, separated by YAML document markers.
func PrintAll(w io.Writer) error {
	files, err := embeddedCRDs.ReadDir(crdsDir)
	if err != nil {
		return fmt.Errorf("failed to read embedded CRDs directory: %w", err)
	}

	if len(files) == 0 {
		return fmt.Errorf("no CRD files found in embedded directory")
	}

	// Sort files for consistent output order
	slices.SortFunc(files, func(a, b fs.DirEntry) int {
		return strings.Compare(a.Name(), b.Name())
	})

	for i, file := range files {
		if file.IsDir() || !strings.HasSuffix(file.Name(), ".yaml") {
			continue
		}

		if i > 0 {
			// YAML document separator
			fmt.Fprintln(w, "---")
		}

		content, err := embeddedCRDs.ReadFile(crdsDir + "/" + file.Name())
		if err != nil {
			return fmt.Errorf("failed to read CRD %s: %w", file.Name(), err)
		}

		if _, err := w.Write(content); err != nil {
			return fmt.Errorf("failed to write CRD %s: %w", file.Name(), err)
		}
	}

	return nil
}
