// Copyright The prometheus-operator Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// MattermostPriorityConfigApplyConfiguration represents a declarative configuration of the MattermostPriorityConfig type for use
// with apply.
//
// MattermostPriorityConfig configures the parameters related to the priority of the message.
type MattermostPriorityConfigApplyConfiguration struct {
	// priority adds the priority label to the message.
	// Possible values are `urgent`, `important` and `standard`.
	Priority *string `json:"priority,omitempty"`
	// requestedAck defines whether the message requires an acknowledgement from users.
	//
	// If set to true, the message will be marked as requiring an acknowledgment
	// from the users by displaying a checkmark icon next to the message.
	//
	// Keep in mind that this requires the message priority to be set to `important` or `urgent`.
	//
	// Only for enterprise version of Mattermost.
	RequestedAck *bool `json:"requestedAck,omitempty"`
	// persistentNotifications defines whether the message notification will be persisted.
	//
	// This can be used only with the `urgent` messages.
	// If set to true recipients will receive a persistent notification
	// every five minutes until they acknowledge the message.
	//
	// Only for enterprise version of Mattermost.
	PersistentNotifications *bool `json:"persistentNotifications,omitempty"`
}

// MattermostPriorityConfigApplyConfiguration constructs a declarative configuration of the MattermostPriorityConfig type for use with
// apply.
func MattermostPriorityConfig() *MattermostPriorityConfigApplyConfiguration {
	return &MattermostPriorityConfigApplyConfiguration{}
}

// WithPriority sets the Priority field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Priority field is set to the value of the last call.
func (b *MattermostPriorityConfigApplyConfiguration) WithPriority(value string) *MattermostPriorityConfigApplyConfiguration {
	b.Priority = &value
	return b
}

// WithRequestedAck sets the RequestedAck field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequestedAck field is set to the value of the last call.
func (b *MattermostPriorityConfigApplyConfiguration) WithRequestedAck(value bool) *MattermostPriorityConfigApplyConfiguration {
	b.RequestedAck = &value
	return b
}

// WithPersistentNotifications sets the PersistentNotifications field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PersistentNotifications field is set to the value of the last call.
func (b *MattermostPriorityConfigApplyConfiguration) WithPersistentNotifications(value bool) *MattermostPriorityConfigApplyConfiguration {
	b.PersistentNotifications = &value
	return b
}
