// Copyright The prometheus-operator Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	monitoringv1alpha1 "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1alpha1"
)

// EmailThreadingConfigApplyConfiguration represents a declarative configuration of the EmailThreadingConfig type for use
// with apply.
type EmailThreadingConfigApplyConfiguration struct {
	// threadByDate defines what granularity of current date to thread by. Accepted values: Daily, None.
	// (None means group by alert group key, no date).
	ThreadByDate *monitoringv1alpha1.ThreadByDateType `json:"threadByDate,omitempty"`
}

// EmailThreadingConfigApplyConfiguration constructs a declarative configuration of the EmailThreadingConfig type for use with
// apply.
func EmailThreadingConfig() *EmailThreadingConfigApplyConfiguration {
	return &EmailThreadingConfigApplyConfiguration{}
}

// WithThreadByDate sets the ThreadByDate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ThreadByDate field is set to the value of the last call.
func (b *EmailThreadingConfigApplyConfiguration) WithThreadByDate(value monitoringv1alpha1.ThreadByDateType) *EmailThreadingConfigApplyConfiguration {
	b.ThreadByDate = &value
	return b
}
