// Copyright The prometheus-operator Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	monitoringv1 "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1"
	v1 "k8s.io/api/core/v1"
)

// IncidentioConfigApplyConfiguration represents a declarative configuration of the IncidentioConfig type for use
// with apply.
//
// IncidentioConfig configures notifications via Incident.io.
// See https://prometheus.io/docs/alerting/latest/configuration/#incidentio_config
// It requires Alertmanager >= v0.29.0.
type IncidentioConfigApplyConfiguration struct {
	// sendResolved defines whether or not to notify about resolved alerts.
	SendResolved *bool `json:"sendResolved,omitempty"`
	// url defines the Incident.io webhook URL to send HTTP POST requests to.
	// urlSecret takes precedence over url. One of urlSecret and url should be defined.
	URL *string `json:"url,omitempty"`
	// urlSecret defines the secret's key that contains the Incident.io webhook URL.
	// urlSecret takes precedence over url. One of urlSecret and url should be defined.
	// The secret needs to be in the same namespace as the AlertmanagerConfig
	// object and accessible by the Prometheus Operator.
	URLSecret *v1.SecretKeySelector `json:"urlSecret,omitempty"`
	// alertSourceToken defines the secret's key that contains the Incident.io alert source token.
	// This token authenticates requests against the Incident.io API.
	AlertSourceToken *v1.SecretKeySelector `json:"alertSourceToken,omitempty"`
	// httpConfig defines the HTTP client configuration for Incident.io webhook requests.
	HTTPConfig *HTTPConfigApplyConfiguration `json:"httpConfig,omitempty"`
	// maxAlerts defines the maximum number of alerts to be sent per Incident.io request.
	// When 0, all alerts are included in the request payload.
	MaxAlerts *int32 `json:"maxAlerts,omitempty"`
	// timeout defines the maximum time to wait for an Incident.io request to complete,
	// before failing the request and allowing it to be retried.
	// It requires Alertmanager >= v0.29.0.
	Timeout *monitoringv1.Duration `json:"timeout,omitempty"`
}

// IncidentioConfigApplyConfiguration constructs a declarative configuration of the IncidentioConfig type for use with
// apply.
func IncidentioConfig() *IncidentioConfigApplyConfiguration {
	return &IncidentioConfigApplyConfiguration{}
}

// WithSendResolved sets the SendResolved field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SendResolved field is set to the value of the last call.
func (b *IncidentioConfigApplyConfiguration) WithSendResolved(value bool) *IncidentioConfigApplyConfiguration {
	b.SendResolved = &value
	return b
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *IncidentioConfigApplyConfiguration) WithURL(value string) *IncidentioConfigApplyConfiguration {
	b.URL = &value
	return b
}

// WithURLSecret sets the URLSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URLSecret field is set to the value of the last call.
func (b *IncidentioConfigApplyConfiguration) WithURLSecret(value v1.SecretKeySelector) *IncidentioConfigApplyConfiguration {
	b.URLSecret = &value
	return b
}

// WithAlertSourceToken sets the AlertSourceToken field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AlertSourceToken field is set to the value of the last call.
func (b *IncidentioConfigApplyConfiguration) WithAlertSourceToken(value v1.SecretKeySelector) *IncidentioConfigApplyConfiguration {
	b.AlertSourceToken = &value
	return b
}

// WithHTTPConfig sets the HTTPConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTPConfig field is set to the value of the last call.
func (b *IncidentioConfigApplyConfiguration) WithHTTPConfig(value *HTTPConfigApplyConfiguration) *IncidentioConfigApplyConfiguration {
	b.HTTPConfig = value
	return b
}

// WithMaxAlerts sets the MaxAlerts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxAlerts field is set to the value of the last call.
func (b *IncidentioConfigApplyConfiguration) WithMaxAlerts(value int32) *IncidentioConfigApplyConfiguration {
	b.MaxAlerts = &value
	return b
}

// WithTimeout sets the Timeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timeout field is set to the value of the last call.
func (b *IncidentioConfigApplyConfiguration) WithTimeout(value monitoringv1.Duration) *IncidentioConfigApplyConfiguration {
	b.Timeout = &value
	return b
}
