// Copyright The prometheus-operator Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// MattermostConfigApplyConfiguration represents a declarative configuration of the MattermostConfig type for use
// with apply.
type MattermostConfigApplyConfiguration struct {
	SendResolved *bool                                          `json:"sendResolved,omitempty"`
	WebhookURL   *v1.SecretKeySelector                          `json:"webhookURL,omitempty"`
	Channel      *string                                        `json:"channel,omitempty"`
	Username     *string                                        `json:"username,omitempty"`
	Text         *string                                        `json:"text,omitempty"`
	IconURL      *string                                        `json:"iconURL,omitempty"`
	IconEmoji    *string                                        `json:"iconEmoji,omitempty"`
	Attachments  []MattermostAttachmentConfigApplyConfiguration `json:"attachments,omitempty"`
	Props        *MattermostPropsConfigApplyConfiguration       `json:"props,omitempty"`
	Priority     *MattermostPriorityConfigApplyConfiguration    `json:"priority,omitempty"`
	HTTPConfig   *HTTPConfigApplyConfiguration                  `json:"httpConfig,omitempty"`
}

// MattermostConfigApplyConfiguration constructs a declarative configuration of the MattermostConfig type for use with
// apply.
func MattermostConfig() *MattermostConfigApplyConfiguration {
	return &MattermostConfigApplyConfiguration{}
}

// WithSendResolved sets the SendResolved field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SendResolved field is set to the value of the last call.
func (b *MattermostConfigApplyConfiguration) WithSendResolved(value bool) *MattermostConfigApplyConfiguration {
	b.SendResolved = &value
	return b
}

// WithWebhookURL sets the WebhookURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WebhookURL field is set to the value of the last call.
func (b *MattermostConfigApplyConfiguration) WithWebhookURL(value v1.SecretKeySelector) *MattermostConfigApplyConfiguration {
	b.WebhookURL = &value
	return b
}

// WithChannel sets the Channel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Channel field is set to the value of the last call.
func (b *MattermostConfigApplyConfiguration) WithChannel(value string) *MattermostConfigApplyConfiguration {
	b.Channel = &value
	return b
}

// WithUsername sets the Username field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Username field is set to the value of the last call.
func (b *MattermostConfigApplyConfiguration) WithUsername(value string) *MattermostConfigApplyConfiguration {
	b.Username = &value
	return b
}

// WithText sets the Text field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Text field is set to the value of the last call.
func (b *MattermostConfigApplyConfiguration) WithText(value string) *MattermostConfigApplyConfiguration {
	b.Text = &value
	return b
}

// WithIconURL sets the IconURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IconURL field is set to the value of the last call.
func (b *MattermostConfigApplyConfiguration) WithIconURL(value string) *MattermostConfigApplyConfiguration {
	b.IconURL = &value
	return b
}

// WithIconEmoji sets the IconEmoji field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IconEmoji field is set to the value of the last call.
func (b *MattermostConfigApplyConfiguration) WithIconEmoji(value string) *MattermostConfigApplyConfiguration {
	b.IconEmoji = &value
	return b
}

// WithAttachments adds the given value to the Attachments field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Attachments field.
func (b *MattermostConfigApplyConfiguration) WithAttachments(values ...*MattermostAttachmentConfigApplyConfiguration) *MattermostConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAttachments")
		}
		b.Attachments = append(b.Attachments, *values[i])
	}
	return b
}

// WithProps sets the Props field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Props field is set to the value of the last call.
func (b *MattermostConfigApplyConfiguration) WithProps(value *MattermostPropsConfigApplyConfiguration) *MattermostConfigApplyConfiguration {
	b.Props = value
	return b
}

// WithPriority sets the Priority field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Priority field is set to the value of the last call.
func (b *MattermostConfigApplyConfiguration) WithPriority(value *MattermostPriorityConfigApplyConfiguration) *MattermostConfigApplyConfiguration {
	b.Priority = value
	return b
}

// WithHTTPConfig sets the HTTPConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTPConfig field is set to the value of the last call.
func (b *MattermostConfigApplyConfiguration) WithHTTPConfig(value *HTTPConfigApplyConfiguration) *MattermostConfigApplyConfiguration {
	b.HTTPConfig = value
	return b
}
