// Copyright The prometheus-operator Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// MattermostAttachmentConfigApplyConfiguration represents a declarative configuration of the MattermostAttachmentConfig type for use
// with apply.
//
// MattermostAttachmentConfig configures attachment parameters for the notifications.
// For more information, please refer to the Mattermost document:
// https://developers.mattermost.com/integrate/reference/message-attachments/
type MattermostAttachmentConfigApplyConfiguration struct {
	// fallback defines a required plain-text summary of the attachment.
	// This is used in notifications, and in clients that don’t support formatted text (e.g. IRC).
	Fallback *string `json:"fallback,omitempty"`
	// color defines a hex color code that will be used as
	// the left border color for the attachment.
	// If not specified, it will default to match the channel sidebar header background color.
	Color *string `json:"color,omitempty"`
	// pretext defines an optional line of text that will be shown above the attachment. Supports @mentions.
	Pretext *string `json:"pretext,omitempty"`
	// text defines the text to be included in the attachment.
	// It can be formatted using Markdown.
	// For long texts, the message is collapsed and a “Show More” link is added to expand the message. Supports @mentions.
	Text *string `json:"text,omitempty"`
	// authorName defines an optional name used to identify the author.
	// It will be included in a small section at the top of the attachment.
	AuthorName *string `json:"authorName,omitempty"`
	// authorLink defines optional URL used to hyperlink the author_name.
	// If no author_name is specified, this field does nothing.
	AuthorLink *string `json:"authorLink,omitempty"`
	// authorIcon defines an optional URL used to display a 16x16 pixel icon beside the author's name.
	AuthorIcon *string `json:"authorIcon,omitempty"`
	// title defines an optional title displayed below the author information in the attachment.
	Title *string `json:"title,omitempty"`
	// titleLink defines an optional URL used to hyperlink the title.
	// If no title is specified, this field does nothing.
	TitleLink *string `json:"titleLink,omitempty"`
	// fields defines a list of fields that are sent with each notification
	// to be displayed in a table format inside the attachment.
	Fields []MattermostFieldApplyConfiguration `json:"fields,omitempty"`
	// thumbURL defines an optional URL to an image file
	// (GIF, JPEG, PNG, BMP, or SVG) that is displayed as a 75x75 pixel thumbnail
	// on the right side of an attachment.
	ThumbURL *string `json:"thumbURL,omitempty"`
	// footer defines an optional line of text that will be displayed at the bottom of the attachment.
	Footer *string `json:"footer,omitempty"`
	// footerIcon defines an optional URL to an image file (GIF, JPEG, PNG, BMP, or SVG)
	// that is displayed as a 16x16 pixel thumbnail before the footer text.
	FooterIcon *string `json:"footerIcon,omitempty"`
	// imageURL defines an optional URL to an image file
	// (GIF, JPEG, PNG, BMP, or SVG) that is displayed inside a message attachment.
	ImageURL *string `json:"imageURL,omitempty"`
}

// MattermostAttachmentConfigApplyConfiguration constructs a declarative configuration of the MattermostAttachmentConfig type for use with
// apply.
func MattermostAttachmentConfig() *MattermostAttachmentConfigApplyConfiguration {
	return &MattermostAttachmentConfigApplyConfiguration{}
}

// WithFallback sets the Fallback field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Fallback field is set to the value of the last call.
func (b *MattermostAttachmentConfigApplyConfiguration) WithFallback(value string) *MattermostAttachmentConfigApplyConfiguration {
	b.Fallback = &value
	return b
}

// WithColor sets the Color field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Color field is set to the value of the last call.
func (b *MattermostAttachmentConfigApplyConfiguration) WithColor(value string) *MattermostAttachmentConfigApplyConfiguration {
	b.Color = &value
	return b
}

// WithPretext sets the Pretext field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Pretext field is set to the value of the last call.
func (b *MattermostAttachmentConfigApplyConfiguration) WithPretext(value string) *MattermostAttachmentConfigApplyConfiguration {
	b.Pretext = &value
	return b
}

// WithText sets the Text field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Text field is set to the value of the last call.
func (b *MattermostAttachmentConfigApplyConfiguration) WithText(value string) *MattermostAttachmentConfigApplyConfiguration {
	b.Text = &value
	return b
}

// WithAuthorName sets the AuthorName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthorName field is set to the value of the last call.
func (b *MattermostAttachmentConfigApplyConfiguration) WithAuthorName(value string) *MattermostAttachmentConfigApplyConfiguration {
	b.AuthorName = &value
	return b
}

// WithAuthorLink sets the AuthorLink field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthorLink field is set to the value of the last call.
func (b *MattermostAttachmentConfigApplyConfiguration) WithAuthorLink(value string) *MattermostAttachmentConfigApplyConfiguration {
	b.AuthorLink = &value
	return b
}

// WithAuthorIcon sets the AuthorIcon field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthorIcon field is set to the value of the last call.
func (b *MattermostAttachmentConfigApplyConfiguration) WithAuthorIcon(value string) *MattermostAttachmentConfigApplyConfiguration {
	b.AuthorIcon = &value
	return b
}

// WithTitle sets the Title field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Title field is set to the value of the last call.
func (b *MattermostAttachmentConfigApplyConfiguration) WithTitle(value string) *MattermostAttachmentConfigApplyConfiguration {
	b.Title = &value
	return b
}

// WithTitleLink sets the TitleLink field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TitleLink field is set to the value of the last call.
func (b *MattermostAttachmentConfigApplyConfiguration) WithTitleLink(value string) *MattermostAttachmentConfigApplyConfiguration {
	b.TitleLink = &value
	return b
}

// WithFields adds the given value to the Fields field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Fields field.
func (b *MattermostAttachmentConfigApplyConfiguration) WithFields(values ...*MattermostFieldApplyConfiguration) *MattermostAttachmentConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithFields")
		}
		b.Fields = append(b.Fields, *values[i])
	}
	return b
}

// WithThumbURL sets the ThumbURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ThumbURL field is set to the value of the last call.
func (b *MattermostAttachmentConfigApplyConfiguration) WithThumbURL(value string) *MattermostAttachmentConfigApplyConfiguration {
	b.ThumbURL = &value
	return b
}

// WithFooter sets the Footer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Footer field is set to the value of the last call.
func (b *MattermostAttachmentConfigApplyConfiguration) WithFooter(value string) *MattermostAttachmentConfigApplyConfiguration {
	b.Footer = &value
	return b
}

// WithFooterIcon sets the FooterIcon field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FooterIcon field is set to the value of the last call.
func (b *MattermostAttachmentConfigApplyConfiguration) WithFooterIcon(value string) *MattermostAttachmentConfigApplyConfiguration {
	b.FooterIcon = &value
	return b
}

// WithImageURL sets the ImageURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImageURL field is set to the value of the last call.
func (b *MattermostAttachmentConfigApplyConfiguration) WithImageURL(value string) *MattermostAttachmentConfigApplyConfiguration {
	b.ImageURL = &value
	return b
}
