// Copyright The prometheus-operator Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// MattermostFieldApplyConfiguration represents a declarative configuration of the MattermostField type for use
// with apply.
type MattermostFieldApplyConfiguration struct {
	Title *string `json:"title,omitempty"`
	Value *string `json:"value,omitempty"`
	Short *bool   `json:"short,omitempty"`
}

// MattermostFieldApplyConfiguration constructs a declarative configuration of the MattermostField type for use with
// apply.
func MattermostField() *MattermostFieldApplyConfiguration {
	return &MattermostFieldApplyConfiguration{}
}

// WithTitle sets the Title field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Title field is set to the value of the last call.
func (b *MattermostFieldApplyConfiguration) WithTitle(value string) *MattermostFieldApplyConfiguration {
	b.Title = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *MattermostFieldApplyConfiguration) WithValue(value string) *MattermostFieldApplyConfiguration {
	b.Value = &value
	return b
}

// WithShort sets the Short field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Short field is set to the value of the last call.
func (b *MattermostFieldApplyConfiguration) WithShort(value bool) *MattermostFieldApplyConfiguration {
	b.Short = &value
	return b
}
