// Copyright The prometheus-operator Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// MattermostAttachmentConfigApplyConfiguration represents a declarative configuration of the MattermostAttachmentConfig type for use
// with apply.
type MattermostAttachmentConfigApplyConfiguration struct {
	Fallback   *string                             `json:"fallback,omitempty"`
	Color      *string                             `json:"color,omitempty"`
	Pretext    *string                             `json:"pretext,omitempty"`
	Text       *string                             `json:"text,omitempty"`
	AuthorName *string                             `json:"authorName,omitempty"`
	AuthorLink *string                             `json:"authorLink,omitempty"`
	AuthorIcon *string                             `json:"authorIcon,omitempty"`
	Title      *string                             `json:"title,omitempty"`
	TitleLink  *string                             `json:"titleLink,omitempty"`
	Fields     []MattermostFieldApplyConfiguration `json:"fields,omitempty"`
	ThumbURL   *string                             `json:"thumbURL,omitempty"`
	Footer     *string                             `json:"footer,omitempty"`
	FooterIcon *string                             `json:"footerIcon,omitempty"`
	ImageURL   *string                             `json:"imageURL,omitempty"`
}

// MattermostAttachmentConfigApplyConfiguration constructs a declarative configuration of the MattermostAttachmentConfig type for use with
// apply.
func MattermostAttachmentConfig() *MattermostAttachmentConfigApplyConfiguration {
	return &MattermostAttachmentConfigApplyConfiguration{}
}

// WithFallback sets the Fallback field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Fallback field is set to the value of the last call.
func (b *MattermostAttachmentConfigApplyConfiguration) WithFallback(value string) *MattermostAttachmentConfigApplyConfiguration {
	b.Fallback = &value
	return b
}

// WithColor sets the Color field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Color field is set to the value of the last call.
func (b *MattermostAttachmentConfigApplyConfiguration) WithColor(value string) *MattermostAttachmentConfigApplyConfiguration {
	b.Color = &value
	return b
}

// WithPretext sets the Pretext field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Pretext field is set to the value of the last call.
func (b *MattermostAttachmentConfigApplyConfiguration) WithPretext(value string) *MattermostAttachmentConfigApplyConfiguration {
	b.Pretext = &value
	return b
}

// WithText sets the Text field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Text field is set to the value of the last call.
func (b *MattermostAttachmentConfigApplyConfiguration) WithText(value string) *MattermostAttachmentConfigApplyConfiguration {
	b.Text = &value
	return b
}

// WithAuthorName sets the AuthorName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthorName field is set to the value of the last call.
func (b *MattermostAttachmentConfigApplyConfiguration) WithAuthorName(value string) *MattermostAttachmentConfigApplyConfiguration {
	b.AuthorName = &value
	return b
}

// WithAuthorLink sets the AuthorLink field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthorLink field is set to the value of the last call.
func (b *MattermostAttachmentConfigApplyConfiguration) WithAuthorLink(value string) *MattermostAttachmentConfigApplyConfiguration {
	b.AuthorLink = &value
	return b
}

// WithAuthorIcon sets the AuthorIcon field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthorIcon field is set to the value of the last call.
func (b *MattermostAttachmentConfigApplyConfiguration) WithAuthorIcon(value string) *MattermostAttachmentConfigApplyConfiguration {
	b.AuthorIcon = &value
	return b
}

// WithTitle sets the Title field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Title field is set to the value of the last call.
func (b *MattermostAttachmentConfigApplyConfiguration) WithTitle(value string) *MattermostAttachmentConfigApplyConfiguration {
	b.Title = &value
	return b
}

// WithTitleLink sets the TitleLink field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TitleLink field is set to the value of the last call.
func (b *MattermostAttachmentConfigApplyConfiguration) WithTitleLink(value string) *MattermostAttachmentConfigApplyConfiguration {
	b.TitleLink = &value
	return b
}

// WithFields adds the given value to the Fields field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Fields field.
func (b *MattermostAttachmentConfigApplyConfiguration) WithFields(values ...*MattermostFieldApplyConfiguration) *MattermostAttachmentConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithFields")
		}
		b.Fields = append(b.Fields, *values[i])
	}
	return b
}

// WithThumbURL sets the ThumbURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ThumbURL field is set to the value of the last call.
func (b *MattermostAttachmentConfigApplyConfiguration) WithThumbURL(value string) *MattermostAttachmentConfigApplyConfiguration {
	b.ThumbURL = &value
	return b
}

// WithFooter sets the Footer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Footer field is set to the value of the last call.
func (b *MattermostAttachmentConfigApplyConfiguration) WithFooter(value string) *MattermostAttachmentConfigApplyConfiguration {
	b.Footer = &value
	return b
}

// WithFooterIcon sets the FooterIcon field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FooterIcon field is set to the value of the last call.
func (b *MattermostAttachmentConfigApplyConfiguration) WithFooterIcon(value string) *MattermostAttachmentConfigApplyConfiguration {
	b.FooterIcon = &value
	return b
}

// WithImageURL sets the ImageURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImageURL field is set to the value of the last call.
func (b *MattermostAttachmentConfigApplyConfiguration) WithImageURL(value string) *MattermostAttachmentConfigApplyConfiguration {
	b.ImageURL = &value
	return b
}
