// Copyright The prometheus-operator Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SlackFieldApplyConfiguration represents a declarative configuration of the SlackField type for use
// with apply.
//
// SlackField configures a single Slack field that is sent with each notification.
// Each field must contain a title, value, and optionally, a boolean value to indicate if the field
// is short enough to be displayed next to other fields designated as short.
// See https://api.slack.com/docs/message-attachments#fields for more information.
type SlackFieldApplyConfiguration struct {
	// title defines the label or header text displayed for this field.
	// This appears as bold text above the field value in the Slack message.
	Title *string `json:"title,omitempty"`
	// value defines the content or data displayed for this field.
	// This appears below the title and can contain plain text or Slack markdown.
	Value *string `json:"value,omitempty"`
	// short determines whether this field can be displayed alongside other short fields.
	// When true, Slack may display this field side by side with other short fields.
	// When false or not specified, the field takes the full width of the message.
	Short *bool `json:"short,omitempty"`
}

// SlackFieldApplyConfiguration constructs a declarative configuration of the SlackField type for use with
// apply.
func SlackField() *SlackFieldApplyConfiguration {
	return &SlackFieldApplyConfiguration{}
}

// WithTitle sets the Title field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Title field is set to the value of the last call.
func (b *SlackFieldApplyConfiguration) WithTitle(value string) *SlackFieldApplyConfiguration {
	b.Title = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *SlackFieldApplyConfiguration) WithValue(value string) *SlackFieldApplyConfiguration {
	b.Value = &value
	return b
}

// WithShort sets the Short field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Short field is set to the value of the last call.
func (b *SlackFieldApplyConfiguration) WithShort(value bool) *SlackFieldApplyConfiguration {
	b.Short = &value
	return b
}
