// Copyright The prometheus-operator Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apismonitoringv1alpha1 "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1alpha1"
	internalinterfaces "github.com/prometheus-operator/prometheus-operator/pkg/client/informers/externalversions/internalinterfaces"
	monitoringv1alpha1 "github.com/prometheus-operator/prometheus-operator/pkg/client/listers/monitoring/v1alpha1"
	versioned "github.com/prometheus-operator/prometheus-operator/pkg/client/versioned"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AlertmanagerConfigInformer provides access to a shared informer and lister for
// AlertmanagerConfigs. Prefer using the type-safe variant (see [TypedAlertmanagerConfigInformer]).
type AlertmanagerConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() monitoringv1alpha1.AlertmanagerConfigLister
}

// TypedAlertmanagerConfigInformer provides access to a shared informer and lister for
// AlertmanagerConfigs, including the type-safe TypedInformer variant.
// It is a superset of AlertmanagerConfigInformer.
type TypedAlertmanagerConfigInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() AlertmanagerConfigIndexInformer
	Lister() monitoringv1alpha1.AlertmanagerConfigLister
}

// AlertmanagerConfigIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type AlertmanagerConfigIndexInformer cache.TypedSharedIndexInformer[*apismonitoringv1alpha1.AlertmanagerConfig]

// AlertmanagerConfigHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for AlertmanagerConfig.
type AlertmanagerConfigHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apismonitoringv1alpha1.AlertmanagerConfig]

// AlertmanagerConfigDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for AlertmanagerConfig.
type AlertmanagerConfigDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apismonitoringv1alpha1.AlertmanagerConfig]

// AlertmanagerConfigFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for AlertmanagerConfig.
type AlertmanagerConfigFilteringHandler = cache.TypedFilteringResourceEventHandler[*apismonitoringv1alpha1.AlertmanagerConfig]

// AlertmanagerConfigIndexers is a specialization of [cache.TypedIndexers] for AlertmanagerConfig.
type AlertmanagerConfigIndexers = cache.TypedIndexers[*apismonitoringv1alpha1.AlertmanagerConfig]

// DeletedAlertmanagerConfig is a specialization of [cache.DeletedObject] for AlertmanagerConfig.
type DeletedAlertmanagerConfig = cache.DeletedObject[*apismonitoringv1alpha1.AlertmanagerConfig]

type alertmanagerConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAlertmanagerConfigInformer constructs a new informer for AlertmanagerConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedAlertmanagerConfigInformer]).
func NewAlertmanagerConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewAlertmanagerConfigInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedAlertmanagerConfigInformer constructs a new informer for AlertmanagerConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedAlertmanagerConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers AlertmanagerConfigIndexers) AlertmanagerConfigIndexInformer {
	return NewTypedAlertmanagerConfigInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredAlertmanagerConfigInformer constructs a new informer for AlertmanagerConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredAlertmanagerConfigInformer]).
func NewFilteredAlertmanagerConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedAlertmanagerConfigInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredAlertmanagerConfigInformer constructs a new informer for AlertmanagerConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredAlertmanagerConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers AlertmanagerConfigIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) AlertmanagerConfigIndexInformer {
	return NewTypedAlertmanagerConfigInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewAlertmanagerConfigInformerWithOptions constructs a new informer for AlertmanagerConfig type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedAlertmanagerConfigInformerWithOptions]).
func NewAlertmanagerConfigInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedAlertmanagerConfigInformerWithOptions(client, namespace, options)
}

// NewTypedAlertmanagerConfigInformerWithOptions constructs a new informer for AlertmanagerConfig type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedAlertmanagerConfigInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) AlertmanagerConfigIndexInformer {
	gvr := schema.GroupVersionResource{Group: "monitoring.coreos.com", Version: "v1alpha1", Resource: "alertmanagerconfigs"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apismonitoringv1alpha1.AlertmanagerConfig](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.MonitoringV1alpha1().AlertmanagerConfigs(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.MonitoringV1alpha1().AlertmanagerConfigs(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.MonitoringV1alpha1().AlertmanagerConfigs(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.MonitoringV1alpha1().AlertmanagerConfigs(namespace).Watch(ctx, opts)
			},
		}, client),
		&apismonitoringv1alpha1.AlertmanagerConfig{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *alertmanagerConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedAlertmanagerConfigInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *alertmanagerConfigInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *alertmanagerConfigInformer) TypedInformer() AlertmanagerConfigIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apismonitoringv1alpha1.AlertmanagerConfig](f.factory.InformerFor(&apismonitoringv1alpha1.AlertmanagerConfig{}, f.defaultInformer))
}

func (f *alertmanagerConfigInformer) Lister() monitoringv1alpha1.AlertmanagerConfigLister {
	return monitoringv1alpha1.NewAlertmanagerConfigLister(f.Informer().GetIndexer())
}

// ToTypedAlertmanagerConfigInformer converts an untyped informer into a TypedAlertmanagerConfigInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *AlertmanagerConfig. If that is not the case, calling type-safe methods of the returned
// TypedAlertmanagerConfigInformer leads to runtime panics. A safer alternative is to pass
// around a TypedAlertmanagerConfigInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedAlertmanagerConfigInformer(informer AlertmanagerConfigInformer) TypedAlertmanagerConfigInformer {
	if informer, ok := informer.(TypedAlertmanagerConfigInformer); ok {
		return informer
	}
	return &alertmanagerConfigTypedInformerAdapter{informer}
}

type alertmanagerConfigTypedInformerAdapter struct {
	AlertmanagerConfigInformer
}

func (a *alertmanagerConfigTypedInformerAdapter) TypedInformer() AlertmanagerConfigIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apismonitoringv1alpha1.AlertmanagerConfig](a.Informer())
}

// ToAlertmanagerConfigIndexInformer converts an untyped informer into a AlertmanagerConfigIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *AlertmanagerConfig. If that is not the case, calling type-safe methods of the returned
// AlertmanagerConfigIndexInformer leads to runtime panics. A safer alternative is to pass
// around a AlertmanagerConfigIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToAlertmanagerConfigIndexInformer(informer cache.SharedIndexInformer) AlertmanagerConfigIndexInformer {
	if informer, ok := informer.(AlertmanagerConfigIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apismonitoringv1alpha1.AlertmanagerConfig](informer)
}
