// Copyright The prometheus-operator Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
)

// HTTPConfigWithoutTLSApplyConfiguration represents a declarative configuration of the HTTPConfigWithoutTLS type for use
// with apply.
type HTTPConfigWithoutTLSApplyConfiguration struct {
	Authorization     *SafeAuthorizationApplyConfiguration `json:"authorization,omitempty"`
	BasicAuth         *BasicAuthApplyConfiguration         `json:"basicAuth,omitempty"`
	OAuth2            *OAuth2ApplyConfiguration            `json:"oauth2,omitempty"`
	BearerTokenSecret *corev1.SecretKeySelector            `json:"bearerTokenSecret,omitempty"`
	FollowRedirects   *bool                                `json:"followRedirects,omitempty"`
	EnableHTTP2       *bool                                `json:"enableHttp2,omitempty"`
	HTTPHeaders       map[string]string                    `json:"httpHeaders,omitempty"`
}

// HTTPConfigWithoutTLSApplyConfiguration constructs a declarative configuration of the HTTPConfigWithoutTLS type for use with
// apply.
func HTTPConfigWithoutTLS() *HTTPConfigWithoutTLSApplyConfiguration {
	return &HTTPConfigWithoutTLSApplyConfiguration{}
}

// WithAuthorization sets the Authorization field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Authorization field is set to the value of the last call.
func (b *HTTPConfigWithoutTLSApplyConfiguration) WithAuthorization(value *SafeAuthorizationApplyConfiguration) *HTTPConfigWithoutTLSApplyConfiguration {
	b.Authorization = value
	return b
}

// WithBasicAuth sets the BasicAuth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BasicAuth field is set to the value of the last call.
func (b *HTTPConfigWithoutTLSApplyConfiguration) WithBasicAuth(value *BasicAuthApplyConfiguration) *HTTPConfigWithoutTLSApplyConfiguration {
	b.BasicAuth = value
	return b
}

// WithOAuth2 sets the OAuth2 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OAuth2 field is set to the value of the last call.
func (b *HTTPConfigWithoutTLSApplyConfiguration) WithOAuth2(value *OAuth2ApplyConfiguration) *HTTPConfigWithoutTLSApplyConfiguration {
	b.OAuth2 = value
	return b
}

// WithBearerTokenSecret sets the BearerTokenSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BearerTokenSecret field is set to the value of the last call.
func (b *HTTPConfigWithoutTLSApplyConfiguration) WithBearerTokenSecret(value corev1.SecretKeySelector) *HTTPConfigWithoutTLSApplyConfiguration {
	b.BearerTokenSecret = &value
	return b
}

// WithFollowRedirects sets the FollowRedirects field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FollowRedirects field is set to the value of the last call.
func (b *HTTPConfigWithoutTLSApplyConfiguration) WithFollowRedirects(value bool) *HTTPConfigWithoutTLSApplyConfiguration {
	b.FollowRedirects = &value
	return b
}

// WithEnableHTTP2 sets the EnableHTTP2 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnableHTTP2 field is set to the value of the last call.
func (b *HTTPConfigWithoutTLSApplyConfiguration) WithEnableHTTP2(value bool) *HTTPConfigWithoutTLSApplyConfiguration {
	b.EnableHTTP2 = &value
	return b
}

// WithHTTPHeaders puts the entries into the HTTPHeaders field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the HTTPHeaders field,
// overwriting an existing map entries in HTTPHeaders field with the same key.
func (b *HTTPConfigWithoutTLSApplyConfiguration) WithHTTPHeaders(entries map[string]string) *HTTPConfigWithoutTLSApplyConfiguration {
	if b.HTTPHeaders == nil && len(entries) > 0 {
		b.HTTPHeaders = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.HTTPHeaders[k] = v
	}
	return b
}
