// Copyright The prometheus-operator Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
)

// HTTPConfigWithTLSFilesApplyConfiguration represents a declarative configuration of the HTTPConfigWithTLSFiles type for use
// with apply.
type HTTPConfigWithTLSFilesApplyConfiguration struct {
	HTTPConfigWithoutTLSApplyConfiguration `json:",inline"`
	TLSConfig                              *TLSConfigApplyConfiguration `json:"tlsConfig,omitempty"`
}

// HTTPConfigWithTLSFilesApplyConfiguration constructs a declarative configuration of the HTTPConfigWithTLSFiles type for use with
// apply.
func HTTPConfigWithTLSFiles() *HTTPConfigWithTLSFilesApplyConfiguration {
	return &HTTPConfigWithTLSFilesApplyConfiguration{}
}

// WithAuthorization sets the Authorization field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Authorization field is set to the value of the last call.
func (b *HTTPConfigWithTLSFilesApplyConfiguration) WithAuthorization(value *SafeAuthorizationApplyConfiguration) *HTTPConfigWithTLSFilesApplyConfiguration {
	b.HTTPConfigWithoutTLSApplyConfiguration.Authorization = value
	return b
}

// WithBasicAuth sets the BasicAuth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BasicAuth field is set to the value of the last call.
func (b *HTTPConfigWithTLSFilesApplyConfiguration) WithBasicAuth(value *BasicAuthApplyConfiguration) *HTTPConfigWithTLSFilesApplyConfiguration {
	b.HTTPConfigWithoutTLSApplyConfiguration.BasicAuth = value
	return b
}

// WithOAuth2 sets the OAuth2 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OAuth2 field is set to the value of the last call.
func (b *HTTPConfigWithTLSFilesApplyConfiguration) WithOAuth2(value *OAuth2ApplyConfiguration) *HTTPConfigWithTLSFilesApplyConfiguration {
	b.HTTPConfigWithoutTLSApplyConfiguration.OAuth2 = value
	return b
}

// WithBearerTokenSecret sets the BearerTokenSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BearerTokenSecret field is set to the value of the last call.
func (b *HTTPConfigWithTLSFilesApplyConfiguration) WithBearerTokenSecret(value corev1.SecretKeySelector) *HTTPConfigWithTLSFilesApplyConfiguration {
	b.HTTPConfigWithoutTLSApplyConfiguration.BearerTokenSecret = &value
	return b
}

// WithFollowRedirects sets the FollowRedirects field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FollowRedirects field is set to the value of the last call.
func (b *HTTPConfigWithTLSFilesApplyConfiguration) WithFollowRedirects(value bool) *HTTPConfigWithTLSFilesApplyConfiguration {
	b.HTTPConfigWithoutTLSApplyConfiguration.FollowRedirects = &value
	return b
}

// WithEnableHTTP2 sets the EnableHTTP2 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnableHTTP2 field is set to the value of the last call.
func (b *HTTPConfigWithTLSFilesApplyConfiguration) WithEnableHTTP2(value bool) *HTTPConfigWithTLSFilesApplyConfiguration {
	b.HTTPConfigWithoutTLSApplyConfiguration.EnableHTTP2 = &value
	return b
}

// WithHTTPHeaders puts the entries into the HTTPHeaders field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the HTTPHeaders field,
// overwriting an existing map entries in HTTPHeaders field with the same key.
func (b *HTTPConfigWithTLSFilesApplyConfiguration) WithHTTPHeaders(entries map[string]string) *HTTPConfigWithTLSFilesApplyConfiguration {
	if b.HTTPConfigWithoutTLSApplyConfiguration.HTTPHeaders == nil && len(entries) > 0 {
		b.HTTPConfigWithoutTLSApplyConfiguration.HTTPHeaders = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.HTTPConfigWithoutTLSApplyConfiguration.HTTPHeaders[k] = v
	}
	return b
}

// WithTLSConfig sets the TLSConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLSConfig field is set to the value of the last call.
func (b *HTTPConfigWithTLSFilesApplyConfiguration) WithTLSConfig(value *TLSConfigApplyConfiguration) *HTTPConfigWithTLSFilesApplyConfiguration {
	b.TLSConfig = value
	return b
}
