// Copyright The prometheus-operator Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1 "k8s.io/api/core/v1"
)

// SafeHTTPHeaderApplyConfiguration represents a declarative configuration of the SafeHTTPHeader type for use
// with apply.
type SafeHTTPHeaderApplyConfiguration struct {
	Values  []string               `json:"values,omitempty"`
	Secrets []v1.SecretKeySelector `json:"secrets,omitempty"`
}

// SafeHTTPHeaderApplyConfiguration constructs a declarative configuration of the SafeHTTPHeader type for use with
// apply.
func SafeHTTPHeader() *SafeHTTPHeaderApplyConfiguration {
	return &SafeHTTPHeaderApplyConfiguration{}
}

// WithValues adds the given value to the Values field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Values field.
func (b *SafeHTTPHeaderApplyConfiguration) WithValues(values ...string) *SafeHTTPHeaderApplyConfiguration {
	for i := range values {
		b.Values = append(b.Values, values[i])
	}
	return b
}

// WithSecrets adds the given value to the Secrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Secrets field.
func (b *SafeHTTPHeaderApplyConfiguration) WithSecrets(values ...v1.SecretKeySelector) *SafeHTTPHeaderApplyConfiguration {
	for i := range values {
		b.Secrets = append(b.Secrets, values[i])
	}
	return b
}
