// Copyright The prometheus-operator Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1"
	monitoringv1 "github.com/prometheus-operator/prometheus-operator/pkg/client/applyconfiguration/monitoring/v1"
	typedmonitoringv1 "github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakePrometheusRules implements PrometheusRuleInterface
type fakePrometheusRules struct {
	*gentype.FakeClientWithListAndApply[*v1.PrometheusRule, *v1.PrometheusRuleList, *monitoringv1.PrometheusRuleApplyConfiguration]
	Fake *FakeMonitoringV1
}

func newFakePrometheusRules(fake *FakeMonitoringV1, namespace string) typedmonitoringv1.PrometheusRuleInterface {
	return &fakePrometheusRules{
		gentype.NewFakeClientWithListAndApply[*v1.PrometheusRule, *v1.PrometheusRuleList, *monitoringv1.PrometheusRuleApplyConfiguration](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("prometheusrules"),
			v1.SchemeGroupVersion.WithKind("PrometheusRule"),
			func() *v1.PrometheusRule { return &v1.PrometheusRule{} },
			func() *v1.PrometheusRuleList { return &v1.PrometheusRuleList{} },
			func(dst, src *v1.PrometheusRuleList) { dst.ListMeta = src.ListMeta },
			func(list *v1.PrometheusRuleList) []*v1.PrometheusRule { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.PrometheusRuleList, items []*v1.PrometheusRule) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
