---
name: Check for Vulnerabilities

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  check-for-vulnerabilities:
    name: Check for Vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Import environment variables from file
        run: cat ".github/env" >> "$GITHUB_ENV"

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: '${{ env.golang-version }}'
          check-latest: true

      - name: Run govulncheck
        uses: golang/govulncheck-action@032d45514ae346b1db93c04b0c90b841c370344f # v1.1.0
        with:
          go-package: ./...
          output-format: sarif
          output-file: govulncheck.sarif

      - name: Upload SARIF File
        uses: github/codeql-action/upload-sarif@b96794f015dfd88f77b49b1c93e0fa7110f94c63 # v4.38.0
        with:
          sarif_file: govulncheck.sarif
          category: govulncheck
