name: govulncheck
on:
  pull_request:
    paths:
      - VERSION
      - .github/workflows/govulncheck.yml
  push:
    branches:
      - 'release-*'
      - main
      - master
  schedule:
    - cron: '30 4 * * *'

permissions:
  contents: read

# To cancel running workflow when new commits pushed in a pull request
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  check-govulncheck:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
    - uses: actions/checkout@v6.0.2
    - name: Import environment variables from file
      run: cat ".github/env" >> "$GITHUB_ENV"
    - uses: actions/setup-go@v6.4.0
      with:
        go-version: '${{ env.golang-version }}'
        check-latest: true
    - id: govulncheck
      uses: golang/govulncheck-action@v1.0.4
      with:
        go-version-input: '${{ env.golang-version }}'
        go-package: ./...
        repo-checkout: false
