name: Spell Check

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run cSpell
        uses: streetsidesoftware/cspell-action@6f3c77c1406bc930f944ba97e9801a22e42caf58 # v9.1.0
        with:
          incremental_files_only: false
          files:  "**/*.{md,yaml,yml}"
          config: '.github/workflows/cspell.json'
