name: Spell Check

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run cSpell
        uses: streetsidesoftware/cspell-action@e0668cf020899e887ee8ad4d173c31738a79eae8 # v9.0.1
        with:
          incremental_files_only: false
          files:  "**/*.{md,yaml,yml}"
          config: '.github/workflows/cspell.json'
